### ISSUE TITLE
Overlay is niet altijd het "bovenste" element

### ISSUE THREAD

**Issue by MicheleNL** [dvens/dvens.github.io#4]
Zie screenshot. Wel toffe overlay!
<img width="950" alt="screen shot 2016-02-12 at 15 42 10" src="https://cloud.githubusercontent.com/assets/13998672/13009917/4c92abea-d19f-11e5-91c3-3113baf51867.png">

**Comment by dvens** [comment]
Opgelost door een position relative op de .layover + z-index van 1.
